language: clojure

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.7.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - curl -O https://download.clojure.org/install/linux-install-1.10.1.469.sh
  - chmod +x linux-install-1.10.1.469.sh
  - sudo ./linux-install-1.10.1.469.sh
  - rm linux-install-1.10.1.469.sh

before_script:
  - make up

script:
  - make test

after_script:
  - make down
