version: '2.0'
services:
  db:
    image: "${PGIMAGE}"   
    container_name: pof 
    ports:
      - "${PGPORT}:5432"
      - "8080:3000"
    volumes:
      - "./init:/docker-entrypoint-initdb.d"
      - "./pgdata:/var/lib/postgresql/data"
    environment:
     POSTGRES_USER:     "${PGUSER}"
     POSTGRES_PASSWORD: "${PGPASSWORD}"
     POSTGRES_DB:       "${PGDATABASE}"
     # PGDATABASE:        "${PGDATABASE}"
