version: '3.1'
services:
  fhir-db:
    image: "${PGIMAGE}"   
    container_name: pof 
    ports:
      - "${PGPORT}:5432"
      volumes:
        - "./pgdata:/var/lib/postgresql/data"
        environment:
          POSTGRES_USER:     "${PGUSER}"
          POSTGRES_PASSWORD: "${PGPASSWORD}"
          POSTGRES_DB:       "${PGDATABASE}"
