version: '3.1'
services:
  elasticsearch: 
    image: nshou/elasticsearch-kibana   
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "5601:5601"
    environment:
      - bootstrap.memory_lock=true
      - cluster.name=alkona
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
 
